;;; replace-at-point-math.el --- Math symbols for replace-at-point. -*- lexical-binding: t; -*-

(require 'replace-at-point)

(defvar replace-at-point-math--symbols
  '(("ne" . "≠")
    ("le" . "≤")
    ("<=" . "≤")
    ("ge" . "≥")
    (">=" . "≥")
    ("asymp" . "≈")
    ("equiv" . "≡")
    ("cong" . "≅")
    ("prop" . "∝")
    ("sim" . "∼")

    ("sum" . "∑")
    ("prod" . "∏")
    ("int" . "∫")
    ("perp" . "⊥")
    ("dot" . "·")

    ("in" . "∈")
    ("notin" . "∉")
    ("sub" . "⊂")
    ("nsub" . "⊄")
    ("sube" . "⊆")
    ("sup" . "⊃")
    ("nsup" . "⊅")
    ("supe" . "⊇")
    ("cap" . "∩")
    ("intersect" . "∩")
    ("cup" . "∪")
    ("union" . "∪")

    ("inf" . "∞")
    ("infin" . "∞")
    ("infty" . "∞")
    ("infinity" . "∞")
    ("empty" . "∅")

    ("mul" . "×")
    ("pm" . "±")
    ("mp" . "∓")
    ("ang" . "∠")
    ("deg" . "°")

    ("AA" . "𝔸")
    ("BB" . "𝔹")
    ("CC" . "ℂ")
    ("DD" . "𝔻")
    ("EE" . "𝔼")
    ("FF" . "𝔽")
    ("GG" . "𝔾")
    ("HH" . "ℍ")
    ("II" . "𝕀")
    ("JJ" . "𝕁")
    ("KK" . "𝕂")
    ("LL" . "𝕃")
    ("MM" . "𝕄")
    ("NN" . "ℕ")
    ("OO" . "𝕆")
    ("PP" . "ℙ")
    ("QQ" . "ℚ")
    ("RR" . "ℝ")
    ("SS" . "𝕊")
    ("TT" . "𝕋")
    ("UU" . "𝕌")
    ("VV" . "𝕍")
    ("WW" . "𝕎")
    ("XX" . "𝕏")
    ("YY" . "𝕐")
    ("ZZ" . "ℤ")

    ("dd" . "ⅆ")
    ("ee" . "ⅇ")
    ("ii" . "ⅈ")
    ("jj" . "ⅉ")

    ("N" . "ℕ")
    ("nat" . "ℕ")
    ("int" . "ℤ")
    ("integer" . "ℤ")
    ("Q" . "ℚ")
    ("rational" . "ℚ")
    ("R" . "ℝ")
    ("real" . "ℝ")
    ("C" . "ℂ")
    ("complex" . "ℂ")
    ("H" . "ℍ")
    ("quaternion" . "ℍ")
    ("S" . "𝕊")
    ("sedenion" . "𝕊"))
  "List of replacements for math symbols.")

(replace-at-point-add replace-at-point-math--symbols)

(provide 'replace-at-point-math)
