;;; replace-at-point-greek.el --- Greek symbols for replace-at-point. -*- lexical-binding: t; -*-

(require 'replace-at-point)

(defvar replace-at-point-greek--symbols
  '(("alpha" . "ɑ")
    ("Alpha" . "Α")
    ("beta" . "β")
    ("Beta" . "Β")
    ("gamma" . "ɣ")
    ("Gamma" . "Ɣ")
    ("delta" . "δ")
    ("Delta" . "Δ")
    ("epsilon" . "ɛ")
    ("Epsilon" . "Ɛ")
    ("zeta" . "ζ")
    ("Zeta" . "Ζ")
    ("eta" . "η")
    ("Eta" . "Η")
    ("theta" . "θ")
    ("Theta" . "Θ")
    ("iota" . "ɩ")
    ("Iota" . "Ɩ")
    ("kappa" . "κ")
    ("Kappa" . "Κ")
    ("lambda" . "λ")
    ("Lambda" . "Λ")
    ("mu" . "μ")
    ("Mu" . "Μ")
    ("nu" . "ν")
    ("Nu" . "Ν")
    ("xi" . "ξ")
    ("Xi" . "Ξ")
    ("omicron" . "ο")
    ("Omicron" . "Ο")
    ("pi" . "π")
    ("Pi" . "Π")
    ("rho" . "ρ")
    ("Rho" . "Ρ")
    ("sigma" . "σ")
    ("Sigma" . "Σ")
    ("tau" . "τ")
    ("Tau" . "Τ")
    ("upsilon" . "υ")
    ("Upsilon" . "Υ")
    ("phi" . "φ")
    ("Phi" . "Φ")
    ("chi" . "χ")
    ("Chi" . "Χ")
    ("psi" . "ψ")
    ("Psi" . "Ψ")
    ("omega" . "ω")
    ("Omega" . "Ω"))
  "List of replacements for greek symbols.")

(replace-at-point-add replace-at-point-greek--symbols)

(provide 'replace-at-point-greek)
